biggus/meta.yaml
Not sure if its worth me doing this PR (since I'm guessing I don't have permissions to push the package to the scitools binstar channel..) but thought I would since there is a disconnect with packages which require the newest tag release.
Worth putting up even if it acts as a reminder for an update.
=> BLD: Updated biggus tag release

cartopy/meta.yaml
Cartopy 0.11.2 has been released so the current dev release version should now be 0.11.3.dev (according to https://www.python.org/dev/peps/pep-0440/ - the examples help). This should also trigger a new build which I'd like to make available since https://github.com/SciTools/cartopy/pull/532 was merged fixing the Natural Earth URL.
=> increment version to 0.11.3.dev

iris/meta.yaml
updating Iris recipe to use 1.7.x, which is currently 1.7.4-dev
this includes the fix for windows building which didn't make it inot the 1.7.3 release
=> iris 1.7.4-dev

cartopy/meta.yaml, geos/build.sh, shapely/meta.yaml
This PR makes adds a 32 build flag in case someone tries to build these recipes in a 32-Linux.  (See https://github.com/ioos/conda-recipes/pull/232)
=> 32 and 64 geos buid flags

cartopy/meta.yaml
This changes dependency to only use PIL on 2.x and use pillow on 3.x.
=> Fix building cartopy packages on Python 3.

ecmwf_grib/meta.yaml
=> Limited ECMWF GRIB building to py2 on OSX. 

cartopy/meta.yaml
Continues the saga from #101 and builds cartopy on an older linux OS.
=> Re-built cartopy for Linux.

scripts/run_docker_build.sh
The `conda install anaconda-client` missed a `--yes` to work properly and that prevented the next 3 lines to be executed.
The lines below are from the circle-ci logs:
```
Proceed ([y]/n)? Invalid choice: conda info
Proceed ([y]/n)? Invalid choice: unset lang
Proceed ([y]/n)? Invalid choice: yum install -y expat-devel git autoconf libtool texinfo check-devel
Proceed ([y]/n)? 
```
=> Fix CircleCI

appveyor.yml, cartopy/meta.yaml
The first change is just for fun.  (I spent the weekend reading AppVeyor's docs.)
The second change should fix the problem we are seeing in #113. One side effect is that the Python 2.7 builds will be slightly slower.
=> Fix AppVeyor builds

cdat-lite/meta.yaml, cfchecker/meta.yaml, ecmwf_grib/meta.yaml, expat/meta.yaml, jasper/meta.yaml, libmo_unpack/meta.yaml, mo_pack/meta.yaml
Ping @ocefpaf - this is coming in a PR for ObviousCI shortly.
FWIW:
```
>>> from glob import glob
>>> import os
>>> recipes = glob('*/meta.yaml')
>>> for recipe in recipes:
...     build = os.path.join(os.path.dirname(recipe), 'bld.bat')
...     print recipe, os.path.exists(build)
... 
biggus/meta.yaml True
cartopy/meta.yaml True
cdat-lite/meta.yaml False
cf_units/meta.yaml True
cfchecker/meta.yaml False
ecmwf_grib/meta.yaml False
expat/meta.yaml True
geos/meta.yaml True
iris/meta.yaml True
jasper/meta.yaml False
libmo_unpack/meta.yaml False
mo_pack/meta.yaml False
obvious-ci/meta.yaml True
owslib/meta.yaml True
proj4/meta.yaml True
pyepsg/meta.yaml True
pyke/meta.yaml True
pyshp/meta.yaml True
python-dateutil/meta.yaml True
pyugrid/meta.yaml True
shapely/meta.yaml True …
```
=> Prepared for ObviousCI which no longer looks at whether a build.sh/bld.bat exists.

iris/meta.yaml
This will make iris build against all possible numpy combinations...
However, there may be some issues to deal with if some dependencies don't support those combinations...
=> Added numpy as a build dependency of iris.

cartopy/bld.bat, cartopy/build.sh, cartopy/meta.yaml, iris/bld.bat, iris/build.sh
iris: from ~27MB to ~2MB
cartopy: ~8MB to ~ 1.5MB
=> Removed the test outputs for cartopy and iris.

cartopy/meta.yaml, proj.4/meta.yaml
I am trying to build the packages in the ioos against Python 3.5 and I noticed a weird bug when building proj.4 on Windows. (See https://github.com/ioos/conda-recipes/issues/588.)
Can we skip this build for now so I can get the rest of the packages going?
Update: Cartopy won't build on win32 without proj.4 and it is failing on win64 (see https://github.com/SciTools/cartopy/issues/699), so I am skipping cartopy for Python 3.5 too.
=> Skip proj.4 build for Win32+Python 3.5 and cartopy for Win+Python 3.5

nc_time_axis/bld.bat, nc_time_axis/build.sh, nc_time_axis/meta.yaml
Once nc-time-axis has been tagged this can be added.
To use nc-time-axis in iris, we need to add this recipe to the scitools channel
=> nc_time_axis recipe

cartopy/meta.yaml
Motivated by https://github.com/matplotlib/basemap/issues/267#issuecomment-225306404 I realized the `scitools` channel is first place people are looking for `cartopy`.
=> Update to 0.14.2

iris-grib/meta.yaml
If this works, it should reinstate testing in the iris_grib build process.
If good, closes #185 ?
=> Add iris as a testing requirement; test via setup.

scripts/run_docker_build.sh
The pinned version of conda-build was quite out of date, so let's remove the pin.
=> Unpin conda-build version for circle

appveyor.yml
Update Windows builds via Appveyor to use conda-build-all. See also #190 and #191.
=> Update appveyor yml to use conda build-all

scripts/run_docker_build.sh
We use a variable to define the optional upload string for uploading build artefacts to anaconda cloud. This variable was not being expanded correctly within the `cat` statement, which was meaning uploading build were failing. This change shifts the variable definition outside of the `cat` call.
=> Change where upload channels var is defined

iris/meta.yaml
fixing a bug introduced in #194
=> iris_grib dependency naming

.travis.yml, appveyor.yml
@bjlittle we don't need to wait for @pelson :wink: 
This should fix the problem in https://github.com/SciTools/conda-recipes-scitools/pull/210#issuecomment-259736232
PS: That is the same version of the bootstrap we are using in `conda-forge` and I believe the `conda-smithy` repo will be the place to support it in the longer term.
=> Fix miniconda download URL

.travis.yml, appveyor.yml, scripts/run_docker_build.sh
pin conda-build to 2.0.6
API changes have broken aspects of conda-build-all
=> pin conda-build to 2.0.6

iris/build.sh, iris/meta.yaml
There's a new(ish) environment variable available during conda builds, which sets the platform-specific file extension for shared objects. This PR updates the Iris recipe to make use of this environment variable, so that we do not have to set it ourselves.
=> Set shared object file extensions using conda-build

.travis.yml, appveyor.yml, imagehash/bld.bat, imagehash/meta.yaml, iris/bld.bat, iris/build.sh, iris/meta.yaml, olefile/meta.yaml, pywavelets/meta.yaml, scripts/run_docker_build.sh
iris-grib ought not to be an iris dependency, as it is not available across platforms and python version
=> remove iris-grib dependency

.travis.yml, appveyor.yml, scripts/run_docker_build.sh
I don't know why there is the restriction to building numpy <= 1.10, now that all the work getting iris to work with different versions of numpy/matplotlib/netcdf has been done.
It has been shown that the iris tests pass in an environment which includes numpy 1.11.1.
I suggest we bump up the upper limit of what version numpy can be (as the PR demonstrates) or we could remove the upper limit altogether and just have
` --matrix-condition "numpy >=1.8"`
?
=> Set numpy condition to allow version 1.11
