SciTools/conda-recipes-scitools

COPYING
COPYING.LESSER

The readme notice states that copies of the licence should be provided. This PR adds COPYING and COPYING.LESSER

added missing licence files

---

appveyor.yml
cartopy/cartopy.win.patch
cartopy/meta.yaml
geos/build.sh
shapely/meta.yaml

Work in progress v0.12.x build of cartopy.

Cartopy v0.12

---

geos/build.sh
shapely/meta.yaml

Note: I've built all of the dependencies without binstar. 
Not to be merged just yet.

Necessary changes for linux64 building on RHEL6.

---

biggus/meta.yaml

Fixes an indexing bug that was uncovered by Iris.

Biggus v0.9.1

---

biggus/build.sh
biggus/meta.yaml
cartopy/build.sh
cartopy/meta.yaml

--single-version-externally-managed please

uneasy-install

---

mo_pack/build.sh
mo_pack/meta.yaml

include mo_pack

---

proj4/meta.yaml

Just testing it out. Not for merging.

Updated proj4 to v4.9.1

---

libmo_unpack/meta.yaml
libmo_unpack/speedup.patch

This includes @pelson's patch to improve performance

Include patch for libmo_unpack 

---

cf_units/bld.bat
cf_units/build.sh
cf_units/meta.yaml

Adding `cf_units`.

---

.travis.yml
shapely/meta.yaml

remove the pelson channel from the .travis.yml
update the shapely release number

-pelson channel, shapely rel

---

ecmwf_grib/build.sh
ecmwf_grib/meta.yaml
ecmwf_grib/py3k.patch

Generally very large due to the extraneous SWIG stuff. It does manage to fix several hundred tests on Python 3. I'm not totally sure it doesn't break anything on Python 2 though, so this might change a little bit.

Patch Grib to work with Python 3.

---

biggus/meta.yaml

Updated biggus recipe to be less representative, but more conda proof.

---

proj4/meta.yaml

Made proj4 python dependent on Windows.

---

appveyor.yml

Windows build matrix

---

ecmwf_grib/meta.yaml
jasper/meta.yaml
libmo_unpack/build.sh
libmo_unpack/meta.yaml
proj4/meta.yaml
scripts/run_docker_build.sh

Works around https://github.com/SciTools/libmo_unpack/issues/18

Re-build libmo-unpack et al.

---

appveyor.yml
pyke/meta.yaml

Not sure if there is a better way to do this.

Pyke for python 3

---

scripts/run_docker_build.sh

Enable Python 3 builds on Circle-CI.

Circle-CI py3k

---

geos/meta.yaml
shapely/bld.bat
shapely/geos_c.win.patch
shapely/meta.yaml
shapely/osx-geos.patch
shapely/stdint.h

Based on https://github.com/ioos/conda-recipes/pull/385.  It works here locally for Python 27 to 35.

Update Shapely to 1.5.11

---

pyugrid/bld.bat
pyugrid/build.sh
pyugrid/meta.yaml

Look at @QuLogic's PR #109 I realized I never sync IOOS pyugrid with scitools.  So... here it is.

Updated to 0.1.6

---

iris/meta.yaml

Unless iris version was not update on purpose I guess we all missed this!

Update iris to v1.8.1

---

cartopy/build.sh
iris/bld.bat

I'm not bumping the build number, I'll let this come through next time we do a release.

Even smaller builds.

---

owslib/bld.bat
owslib/meta.yaml

First step to expand https://github.com/ioos/conda-recipes/pull/554 to OWSLib.

Update OWSLib to 0.9.2

---

cf_units/bld.bat
cf_units/meta.yaml

Updated cf_units to 0.1.1

---

cf_units/meta.yaml

- Refactor of cf_units files.
- Get cf_units ready for drop-in to Iris.

Update cf_units to v1.0.0

---

pyshp/bld.bat
pyshp/build.sh
pyshp/meta.yaml

The AppVeyor failures will go away with #112

Updated pyshp to 1.2.3

---

ecmwf_grib/build.sh
ecmwf_grib/meta.yaml
geos/build.sh
geos/meta.yaml
jasper/build.sh
jasper/meta.yaml
libmo_unpack/build.sh
libmo_unpack/meta.yaml

Just checking...
I am not bumping the build number because we don't really need new builds for these two. (Maybe we don't need the `make check` at all.)

make check

---

udunits2/build.sh
udunits2/meta.yaml

I am not 100% sure about the license.  (Actually [I am 83%](http://www.what-license.com/) sure :wink:)

Updated udunits2 to v2.2.20

---

cartopy/meta.yaml
shapely/bld.bat
shapely/geos_c.win.patch
shapely/meta.yaml
shapely/osx-geos.patch

NB. Will only work once https://github.com/SciTools/cartopy/pull/705 has been merged and the corresponding release has been made.

Bump cartopy to 0.13.1

---

.travis.yml
appveyor.yml
cartopy/meta.yaml
scripts/run_docker_build.sh

Not sure if I changed everything necessary here, but I guess we'll see. I tested all the builds though, so they should be okay.

Enable Python 3.5

---

cf_units/meta.yaml

cf_units 1.1

---

iris/meta.yaml

iris 1.9.2

---

esmf/meta.yaml
esmpy/meta.yaml
netcdf-fortran/build.sh
netcdf-fortran/meta.yaml

Should fix https://github.com/SciTools/conda-recipes-scitools/pull/149#issuecomment-210053682
Ping @pp-mo

Pin libnetcdf

---

.travis.yml
appveyor.yml
scripts/run_docker_build.sh

Notice this is for the dev branch.

Upload to the dev channel

---

cube_browser/meta.yaml

Rebuild of cube-browser.

---

cube_browser/meta.yaml

to test a bug fix for docs on mybinder

cb build number

---

iris-grib/meta.yaml
scripts/run_docker_build.sh

iris grib dev

---

ecmwf_grib/meta.yaml

https://software.ecmwf.int/wiki/display/GRIB/Releases

grib api 1.16

---

cube_browser/meta.yaml
scripts/run_docker_build.sh

cube browser 1.1

---

.travis.yml

Replace `obvious-ci` with `conda-build-all` in `.travis.yml` ~~and `circle.yml`~~.

Use conda-build-all for building recipes

---

scripts/run_docker_build.sh

Use `conda-build-all` to run conda recipes builds on Circle CI. See also #190.

Use conda-build-all for circle CI builds

---

scripts/run_docker_build.sh

Circle builds are still not uploading on a merge... Here's another iteration.

Redefine binstar_token sooner in docker run

---

image-meta-tag/bld.bat
image-meta-tag/build.sh
image-meta-tag/meta.yaml

plausible replacement for #209 (with updates from master)

image-meta-tag

---

README.md
mule/meta.yaml
um_utils/meta.yaml

Just updating the recipes now that a new version is out...
(If you're wondering where vn1.3 went... I was originally planning to add that, but some issues came up which forced us to release vn1.4 earlier than planned; so as far as SciTools etc. are concerned there's not much point having the intermediate version)

Update the recipes for Mule + Utils vn1.4
